### ISSUE TITLE
Error: Unknown XML-RPC tag 'TITLE'

### ISSUE THREAD

**Issue by WoodyPhil** [faisalsami/odoo-xmlrpc#3] opened 2017-01-18 15:20 UTC
Always when i try to connnect, i get the following error:

Error: Unknown XML-RPC tag 'TITLE'

But the login params are fine, i tested them with python. With python it worked correctly.

I executed the file with: node simple.js

**Comment by Thomathan** [comment] 2017-07-11 22:26
Just ran into the same issue and found my problem after some debugging. Besides awful and generic errors from node-xmlrpc, it seems that odoo-xmlrpc does not support HTTPS connections. To support HTTPS, you can replace all instances of `xmlrpc.createClient` with `xmlrpc.createSecureClient`

**Comment by rossigee** [comment] 2017-08-17 01:58
@Thomathan - you may have been using an older version. This was fixed in a recent release. It now checks for 'https' and uses the correct function accordingly...

https://github.com/faisalsami/odoo-xmlrpc/blob/master/lib/index.js#L22

**Comment by rossigee** [comment] 2017-08-17 02:02
@WoodyPhil - I'm getting the same currently. The cause in my case seems to be an nginx redirect returning an HTML page, and so it's trying to parse the 'title' child element as XMLRPC and failing. At the moment, it seems like it might be more of a hosting config related issue rather than a bug in this lib specifically.

**Comment by rossigee** [comment] 2017-08-17 02:47
So it turns out that my problem is also that I've got an old copy of 'odoo-xmlrpc' from doing 'npm install odoo-xmlrpc' :-1: 

Workaround - npm install https://github.com/faisalsami/odoo-xmlrpc

@faisalsami - please ensure the latest version is released via npm and close this ticket. Thanks.

**Comment by natoine** [comment] 2017-08-23 21:37
I met the same error and found it online :
https://github.com/scottgonzalez/node-wordpress/issues/17

**Comment by faisalsami** [comment] 2017-08-26 12:59
Published latest version on npm. Sorry for publishing late.

**Closed as completed by faisalsami** 2017-08-26 12:59 UTC
